# coding: utf-8

"""
    Заказ на ресурсы облака

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.orders_api import OrdersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOrdersApi(unittest.TestCase):
    """OrdersApi unit test stubs"""

    def setUp(self):
        self.api = OrdersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_order(self):
        """Test case for create_order

        Метод создания заказа  # noqa: E501
        """
        pass

    def test_delete_order_by_id(self):
        """Test case for delete_order_by_id

        Метод отмены заказа по ID  # noqa: E501
        """
        pass

    def test_get_all_orders(self):
        """Test case for get_all_orders

        Метод получения списка заказов  # noqa: E501
        """
        pass

    def test_get_order_by_id(self):
        """Test case for get_order_by_id

        Метод получения заказа по ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
