# coding: utf-8

"""
    Заказ на ресурсы облака

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.disk_types_api import DiskTypesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDiskTypesApi(unittest.TestCase):
    """DiskTypesApi unit test stubs"""

    def setUp(self):
        self.api = DiskTypesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_disk_types_list(self):
        """Test case for get_disk_types_list

        Метод получения списка типов дисков  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
