# coding: utf-8

"""
    Заказ на ресурсы облака

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.platforms_api import PlatformsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPlatformsApi(unittest.TestCase):
    """PlatformsApi unit test stubs"""

    def setUp(self):
        self.api = PlatformsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_platform_list(self):
        """Test case for get_platform_list

        Метод получения списка платформ  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
