# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Client(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, fullname: str=None, login: str=None):  # noqa: E501
        """Client - a model defined in Swagger

        :param id: The id of this Client.  # noqa: E501
        :type id: int
        :param fullname: The fullname of this Client.  # noqa: E501
        :type fullname: str
        :param login: The login of this Client.  # noqa: E501
        :type login: str
        """
        self.swagger_types = {
            'id': int,
            'fullname': str,
            'login': str
        }

        self.attribute_map = {
            'id': 'id',
            'fullname': 'fullname',
            'login': 'login'
        }
        self._id = id
        self._fullname = fullname
        self._login = login

    @classmethod
    def from_dict(cls, dikt) -> 'Client':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Client of this Client.  # noqa: E501
        :rtype: Client
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Client.


        :return: The id of this Client.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Client.


        :param id: The id of this Client.
        :type id: int
        """

        self._id = id

    @property
    def fullname(self) -> str:
        """Gets the fullname of this Client.


        :return: The fullname of this Client.
        :rtype: str
        """
        return self._fullname

    @fullname.setter
    def fullname(self, fullname: str):
        """Sets the fullname of this Client.


        :param fullname: The fullname of this Client.
        :type fullname: str
        """
        if fullname is None:
            raise ValueError("Invalid value for `fullname`, must not be `None`")  # noqa: E501

        self._fullname = fullname

    @property
    def login(self) -> str:
        """Gets the login of this Client.


        :return: The login of this Client.
        :rtype: str
        """
        return self._login

    @login.setter
    def login(self, login: str):
        """Sets the login of this Client.


        :param login: The login of this Client.
        :type login: str
        """
        if login is None:
            raise ValueError("Invalid value for `login`, must not be `None`")  # noqa: E501

        self._login = login
