# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse404(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _404: str=None):  # noqa: E501
        """InlineResponse404 - a model defined in Swagger

        :param _404: The _404 of this InlineResponse404.  # noqa: E501
        :type _404: str
        """
        self.swagger_types = {
            '_404': str
        }

        self.attribute_map = {
            '_404': '404'
        }
        self.__404 = _404

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse404':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_404 of this InlineResponse404.  # noqa: E501
        :rtype: InlineResponse404
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _404(self) -> str:
        """Gets the _404 of this InlineResponse404.


        :return: The _404 of this InlineResponse404.
        :rtype: str
        """
        return self.__404

    @_404.setter
    def _404(self, _404: str):
        """Sets the _404 of this InlineResponse404.


        :param _404: The _404 of this InlineResponse404.
        :type _404: str
        """

        self.__404 = _404
